### ISSUE TITLE
aws-load-balancer-controller upgrade doesn't roll the deployment - x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by projuri** [aws/eks-charts#562] opened 2021-07-26 08:12 UTC
**Describe the bug**
Failed to create Ingress object after running upgrade `helm upgrade aws-load-balancer-controller ...` with cert manager disabled.
```
Resource: "networking.k8s.io/v1beta1, Resource=ingresses", GroupVersionKind: "networking.k8s.io/v1beta1, Kind=Ingress"
Name: ".....", Namespace: "....."
for: "STDIN": Internal error occurred: failed calling webhook "vingress.elbv2.k8s.aws": Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/validate-networking-v1beta1-ingress?timeout=10s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "aws-load-balancer-controller-ca")
```

**Steps to reproduce**
1. Execute `helm upgrade aws-load-balancer-controller ...` 
2. Deploy Ingress manifest before certwatcher updates TLS certificates

**Expected outcome**
`helm upgrade` should automatically roll the deployment to guarantee the consistency (related doc https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments).

**Environment**
* Chart name: aws-load-balancer-controller 
* Chart version: 1.2.3
* Kubernetes version: EKS v1.19

**Additional Context**:
As a workaround, a dynamic annotation can be set manually `--set podAnnotations.rollme=$(openssl rand -base64 6)`

**Comment by acim** [comment] 2021-09-18 10:43
This may be a duplicate of https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2071. This other issue is for non-ALB ingresses but the error may be related.

**Comment by kishorj** [comment] 2021-10-04 21:53
@projuri, we will include the ability to reuse TLS secrets on update via the upstream PR https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2264. I'm closing this issue.

**Closed by kishorj** 2021-10-04 21:53 UTC
Labels: bug
