### ISSUE TITLE
[aws-cni-plugin] Add ServiceMonitor for CNI metrics

### ISSUE THREAD

**Issue by sidewinder12s** [aws/eks-charts#502] opened 2021-04-08 01:30 UTC
**Is your feature request related to a problem?**
Can't scrape CNI plugin metrics out of the box with Prometheus. 

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
aws-cni-plugin

**Describe the solution you'd like**
Add a ServiceMonitor, service and toggles to the helm chart

**Describe alternatives you've considered**
Can do it outside the chart, but that's not very nice.

**Comment by jdn5126** [comment] 2023-01-05 22:11
This is a duplicate of https://github.com/aws/amazon-vpc-cni-k8s/issues/2071 , so closing this. VPC CNI itself already exposes metrics for prometheus

**Closed by jdn5126** 2023-01-05 22:11 UTC
Labels: enhancement, help wanted, good first issue
